### ISSUE TITLE
Should use internal Moodle curl class

### ISSUE THREAD

**Issue by danmarsden** [IADLearning/iadlearning#2]
https://github.com/IADLearning/iadlearning/blob/29caee02963604db71d59ffb2198b18ad2386fe8/classes/iad_httprequests.php#L47

Moodle provides an internal Curl class which should be used instead of calling curl directly - One reason this should be used is that many sites sit behind a firewall and require the use of a web proxy to allow outgoing connections. The internal Moodle curl class handles that for you.

**Comment by IADLearning** [comment]
Code has been changed to use Moodle CURL class.
